base:
  random_state: 42

prepare:
  test_size: 0.2
  trainset_path: data/trainset.csv
  testset_path: data/testset.csv

train:
  alpha: [0.00001, 0.0001, 0.001, 0.1, 1]
  l1_ratio: [0.5, 0.9, 0.99, 0.999, 1]
  kfold_n_splits: 5
  scoring_function: 'r2'
  model_path: models/model.pkl
  hpo_metrics_path: reports/hpo-metrics.json

evaluate:
  metrics_path: reports/metrics.json
